apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: exampleapps.apps.fabianism.us
spec:
  group: apps.fabianism.us
  names:
    kind: ExampleApp
    listKind: ExampleAppList
    plural: exampleapps
    singular: exampleapp
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
