apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: example-operator
  template:
    metadata:
      labels:
        name: example-operator
    spec:
      serviceAccountName: example-operator
      containers:
        - name: example-operator
          # Replace this with the built image name
          image: "{{ REPLACE_IMAGE }}"
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "example-operator"
